name: py3
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.12.12=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.12=h7f8727e_0
  - pip=23.3.1=py38h06a4308_0
  - python=3.8.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - amqp==5.2.0
      - astropy==5.0.3
      - astroquery==0.4.6
      - backports-zoneinfo==0.2.1
      - bcrypt==4.1.2
      - beautifulsoup4==4.12.2
      - billiard==4.2.0
      - celery==5.3.0
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==2.0.12
      - click==8.1.7
      - click-didyoumean==0.3.0
      - click-plugins==1.1.1
      - click-repl==0.3.0
      - cryptography==41.0.7
      - colorlog==6.8.2
      - dill==0.3.7
      - globus-sdk==3.34.0
      - greenlet==3.0.3
      - html5lib==1.1
      - humanize==3.10.0
      - idna==3.6
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.1
      - jaraco-classes==3.3.0
      - jeepney==0.8.0
      - keyring==24.3.0
      - kombu==5.3.4
      - more-itertools==10.1.0
      - numpy==1.21.2
      - packaging==23.2
      - pandas==1.4.1
      - paramiko==3.4.0
      - parsl==2023.9.25
      - prompt-toolkit==3.0.43
      - psutil==5.9.7
      - psycopg2-binary==2.8.6
      - pycparser==2.21
      - pyerfa==2.0.0.3
      - pyjwt==2.8.0
      - pynacl==1.5.0
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyvo==1.5
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - requests==2.27.1
      - scipy==1.7.3
      - secretstorage==3.3.3
      - setproctitle==1.3.3
      - six==1.16.0
      - soupsieve==2.5
      - spiceypy==5.0.1
      - sqlalchemy==1.4.32
      - tblib==3.0.0
      - typeguard==2.13.3
      - typing-extensions==4.9.0
      - tzdata==2023.4
      - urllib3==1.26.18
      - vine==5.1.0
      - wcwidth==0.2.12
      - webencodings==0.5.1
      - zipp==3.17.0
